// ---------------------------------------------------------------------------
// VectiSuite UI · embed-progmem
// Author: Chinmoy Bhuyan <chinmoy@joulepoint.com>  (c) 2026 VectiVolt — Apache-2.0
// ---------------------------------------------------------------------------
//
// For each built Svelte app, gzips the single-file dist HTML and writes the
// bytes into the corresponding *_ui_gz.h PROGMEM array.

import { readFileSync, writeFileSync, statSync } from "node:fs";
import { gzipSync } from "node:zlib";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, "..");
const libs = resolve(here, "../../libraries");

const MAP = [
  { app: "dash",   lib: "VectiDash",   sym: "DASH_UI_HTML_GZ"   },
  { app: "ota",    lib: "VectiOTA",    sym: "OTA_UI_HTML_GZ"    },
  { app: "serial", lib: "VectiSerial", sym: "SERIAL_UI_HTML_GZ" },
  { app: "net",    lib: "VectiNet",    sym: "NET_UI_HTML_GZ"    },
];

const emitBytes = (name, data) => {
  const lines = [`const uint8_t ${name}[] PROGMEM = {`];
  for (let i = 0; i < data.length; i += 16) {
    lines.push("  " + Array.from(data.slice(i, i + 16))
      .map(b => "0x" + b.toString(16).padStart(2, "0")).join(", ") + ",");
  }
  lines.push("};");
  lines.push(`const size_t ${name}_LEN = sizeof(${name});`);
  return lines.join("\n");
};

for (const { app, lib, sym } of MAP) {
  const src = resolve(root, `dist/${app}/index.html`);
  try { statSync(src); } catch { console.log(`  ⏭  ${app} (no dist) — skip`); continue; }
  const raw = readFileSync(src);
  const gz  = gzipSync(raw, { level: 9 });
  const out = resolve(libs, `${lib}/src/${lib}_ui_gz.h`);
  writeFileSync(out,
`// Auto-generated by ui/scripts/embed-progmem.js — do not edit by hand.
// Source: ui/apps/${app}/  →  ui/dist/${app}/index.html  →  gzip
// Author: Chinmoy Bhuyan <chinmoy@joulepoint.com>  (c) 2026 VectiVolt — Apache-2.0
#pragma once
#include <Arduino.h>
namespace vecti {
${emitBytes(sym, gz)}
} // namespace vecti
`);
  console.log(`  ✓ ${lib}: ${raw.length} HTML → ${gz.length} gz  (${(100*(1-gz.length/raw.length)).toFixed(1)}% smaller) → ${lib}_ui_gz.h`);
}
