# ---------------------------------------------------------------------------
# JouleSuite for ESP32 / ESP8266 — JouleOTA · JouleSerial · JouleNet · JouleDash
# Author: Chinmoy Bhuyan
# Email:  dikibhuyan@gmail.com
# (c) 2026 — MIT License
# ---------------------------------------------------------------------------

#!/usr/bin/env python3
"""Pre-gzip each Joule* library's embedded HTML and write a *_ui_gz.h
sibling header containing the compressed bytes as a PROGMEM uint8_t array.

The library serves these with `Content-Encoding: gzip` so the browser
decompresses transparently. Result: ~14 KB HTML → ~3-5 KB on the wire,
which is the difference between "loads on a fresh router 1m away" and
"loads even at RSSI -90 dBm from across the building".

Title / brand substitutions can't happen on gzipped bytes, so the library
takes a different path: the gz blob serves an "unsubstituted" template
that uses runtime DOM updates (via JS) to fill in title/brand from the
/api/info JSON. We keep the original *_ui.h around for any caller that
wants the substitutable version.

Output schema (e.g. for JouleOTA):
    namespace joule {
      extern const uint8_t  OTA_UI_HTML_GZ[]    PROGMEM;
      extern const size_t   OTA_UI_HTML_GZ_LEN;
    }
"""
import gzip, re, pathlib, sys

ENTRIES = [
    ("libraries/JouleOTA/src/JouleOTA_ui.h",       "OTA_UI_HTML",    "JouleOTA/src/JouleOTA_ui_gz.h",    "OTA_UI_HTML_GZ"),
    ("libraries/JouleSerial/src/JouleSerial_ui.h", "SERIAL_UI_HTML", "JouleSerial/src/JouleSerial_ui_gz.h","SERIAL_UI_HTML_GZ"),
    ("libraries/JouleNet/src/JouleNet_ui.h",       "NET_UI_HTML",    "JouleNet/src/JouleNet_ui_gz.h",     "NET_UI_HTML_GZ"),
    ("libraries/JouleDash/src/JouleDash_ui.h",     "DASH_UI_HTML",   "JouleDash/src/JouleDash_ui_gz.h",   "DASH_UI_HTML_GZ"),
]

PAT = re.compile(r'R"HTML\((.*?)\)HTML"', re.DOTALL)

def emit_byte_array(name: str, data: bytes) -> str:
    lines = []
    lines.append(f"const uint8_t {name}[] PROGMEM = {{")
    for i in range(0, len(data), 16):
        chunk = data[i:i+16]
        lines.append("  " + ", ".join(f"0x{b:02x}" for b in chunk) + ",")
    lines.append("};")
    lines.append(f"const size_t {name}_LEN = sizeof({name});")
    return "\n".join(lines)

def main():
    root = pathlib.Path(__file__).resolve().parent.parent
    libs_root = root / "libraries"
    for src_rel, src_sym, out_rel, out_sym in ENTRIES:
        src = (root / src_rel)
        if not src.exists():
            print(f"SKIP {src}"); continue
        text = src.read_text()
        m = PAT.search(text)
        if not m:
            print(f"SKIP no R\"HTML(...)HTML\" in {src}"); continue
        html = m.group(1)
        gz = gzip.compress(html.encode("utf-8"), compresslevel=9)

        out = libs_root / out_rel
        out.write_text(
            "// Auto-generated by tools/gzip_ui.py — do not edit by hand.\n"
            "// Pre-compressed copy of the matching *_ui.h HTML literal.\n"
            "#pragma once\n#include <Arduino.h>\nnamespace joule {\n"
            + emit_byte_array(out_sym, gz) + "\n"
            "} // namespace joule\n"
        )
        print(f"{src.name}: {len(html):>6} HTML → {len(gz):>5} gz  ({100*(1-len(gz)/len(html)):4.1f}% smaller) → {out.name}")

if __name__ == "__main__":
    main()
